### ISSUE TITLE
TODO list - Weekly

### ISSUE THREAD

**Issue by DiegoCao** [xingjian-zhang/email-voice-assistant#2]
### Backend Subteam
- [x] Contact with NLP group about API doc
- [x] Finish Test of different email API
- [x] Register a new test email
- [x] #4

---
### NLP Algorithm Subteam

- [x] MVP deliverable - zcs
- [x] Flask requests - qcy

Run out some simple demos on industry-standard APIs
 - [x] Diagflow - rqh
 - [x] Rasa - qjh
